version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: filmoteka-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: filmoteka
      POSTGRES_USER: film_admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/filmoteka.sql:/docker-entrypoint-initdb.d/filmoteka.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
